---
apiVersion: v1
kind: Service
metadata:
  name: wn-sass-web-portal
  labels:
    app: wn-sass-web-portal
spec:
  type: NodePort
  selector:
    app: wn-sass-web-portal
  ports:
  - protocol: TCP
    port: 8080
    name: http
    nodePort: 32222 # Port you’ll use to access app through the Kubernetes IP
    targetPort: 8080 # A Service can map any incoming port to a targetPort. Best the targetPort is set to the same value as the port field.

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: wn-sass-web-portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wn-sass-web-portal
    spec:
      containers:
      - name: wn-sass-web-portal
        # Following docker image hosted in docker hub
        image: sameerat8/wildfly-wn-saas-web:1.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /WNSassWebPortal
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1